FROM python:3.10-slim

RUN pip install --no-cache-dir \
    scikit-learn \
    lightgbm \
    optuna \
    mlflow \
    boto3 \
    pandas \
    numpy \
    pyyaml \
    pyarrow \
    joblib

WORKDIR /workspace
