# 3-node K8S cluster
# Update 129.114.25.83 after terraform apply

[all]
node1 ansible_host=129.114.24.226
node2 ansible_host=192.168.1.12 ansible_ssh_common_args='-o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa_chameleon -W %h:%p cc@129.114.24.226"'
node3 ansible_host=192.168.1.13 ansible_ssh_common_args='-o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa_chameleon -W %h:%p cc@129.114.24.226"'

[all:vars]
ansible_user=cc
ansible_ssh_private_key_file=~/.ssh/id_rsa_chameleon

[control_plane]
node1

[workers]
node1
node2
node3

[storage_nodes]
node1
