apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smartqueue-canary
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SmartQueue-Navidrome/SmartQueue.git
    targetRevision: main
    path: devops/k8s/serving/overlays/canary
  destination:
    server: https://kubernetes.default.svc
    namespace: smartqueue-canary
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
