apiVersion: v1
kind: Service
metadata:
  name: smartqueue-serving
  namespace: smartqueue-prod
  labels:
    app: smartqueue-serving
spec:
  type: NodePort
  selector:
    app: smartqueue-serving
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30800
