apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  namespace: smartqueue-platform
  labels:
    app: navidrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      containers:
        - name: navidrome
          image: node1:5000/smartqueue-navidrome:v1
          ports:
            - containerPort: 4533
          env:
            - name: ND_SCANSCHEDULE
              value: "1h"
            - name: ND_LOGLEVEL
              value: "info"
            - name: ND_BASEURL
              value: ""
          volumeMounts:
            - name: data
              mountPath: /data
            - name: data
              mountPath: /music
              subPath: music
            - name: config
              mountPath: /data/navidrome.toml
              subPath: navidrome.toml
              readOnly: true
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /ping
              port: 4533
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /ping
              port: 4533
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: navidrome-data
        - name: config
          configMap:
            name: navidrome-config
