apiVersion: v1
kind: Service
metadata:
  name: navidrome
  namespace: smartqueue-platform
  labels:
    app: navidrome
spec:
  type: NodePort
  selector:
    app: navidrome
  ports:
    - protocol: TCP
      port: 4533
      targetPort: 4533
      nodePort: 30453
