#!/bin/bash
# Generate Ansible and Kubespray inventory files from Terraform output.
# Run from SmartQueue/devops/tf/kvm/ AFTER terraform apply.
#
# Usage:
#   cd SmartQueue/devops/tf/kvm
#   bash ../../scripts/generate-config.sh
#
# Or pass the floating IP directly:
#   bash ../../scripts/generate-config.sh 129.114.24.226

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEVOPS_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# --- Resolve floating IP ---
if [ -n "${1:-}" ]; then
    FLOATING_IP="$1"
    echo "Using provided floating IP: $FLOATING_IP"
else
    # Try terraform output from current dir or tf/kvm/
    for tf_dir in "." "$DEVOPS_DIR/tf/kvm"; do
        if [ -f "$tf_dir/terraform.tfstate" ]; then
            FLOATING_IP=$(terraform -chdir="$tf_dir" output -raw floating_ip 2>/dev/null || true)
            if [ -n "$FLOATING_IP" ]; then
                echo "Read floating IP from terraform output: $FLOATING_IP"
                break
            fi
        fi
    done
    if [ -z "${FLOATING_IP:-}" ]; then
        echo "ERROR: Could not determine floating IP."
        echo "  Either run from SmartQueue/devops/tf/kvm/ after terraform apply,"
        echo "  or pass it as an argument: $0 <FLOATING_IP>"
        exit 1
    fi
fi

# --- Private IPs (static, defined in terraform variables.tf) ---
NODE1_PRIVATE="192.168.1.11"
NODE2_PRIVATE="192.168.1.12"
NODE3_PRIVATE="192.168.1.13"

# --- Generate Ansible inventory ---
HOSTS_INI="$DEVOPS_DIR/ansible/inventory/hosts.ini"
cat > "$HOSTS_INI" << EOF
# Auto-generated by generate-config.sh — do not edit manually
# Floating IP: ${FLOATING_IP}
# Regenerate: cd SmartQueue/devops/tf/kvm && bash ../../scripts/generate-config.sh

[all]
node1 ansible_host=${FLOATING_IP}
node2 ansible_host=${NODE2_PRIVATE} ansible_ssh_common_args='-o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa_chameleon -W %h:%p cc@${FLOATING_IP}"'
node3 ansible_host=${NODE3_PRIVATE} ansible_ssh_common_args='-o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa_chameleon -W %h:%p cc@${FLOATING_IP}"'

[all:vars]
ansible_user=cc
ansible_ssh_private_key_file=~/.ssh/id_rsa_chameleon

[control_plane]
node1

[workers]
node1
node2
node3

[storage_nodes]
node1
EOF
echo "Generated: $HOSTS_INI"

# --- Generate Kubespray inventory (runs FROM node1, so node1=127.0.0.1) ---
KUBESPRAY_HOSTS="$DEVOPS_DIR/kubespray/inventory/smartqueue/hosts.yaml"
cat > "$KUBESPRAY_HOSTS" << EOF
# Auto-generated by generate-config.sh — do not edit manually
# Kubespray runs FROM node1, so node1 uses 127.0.0.1 with local key.
# Workers use private IPs with the chameleon key.
all:
  hosts:
    node1:
      ansible_host: 127.0.0.1
      ansible_ssh_private_key_file: /home/cc/.ssh/id_rsa
      ip: ${NODE1_PRIVATE}
      access_ip: ${NODE1_PRIVATE}
    node2:
      ansible_host: ${NODE2_PRIVATE}
      ansible_ssh_private_key_file: /home/cc/.ssh/id_rsa_chameleon
      ip: ${NODE2_PRIVATE}
      access_ip: ${NODE2_PRIVATE}
    node3:
      ansible_host: ${NODE3_PRIVATE}
      ansible_ssh_private_key_file: /home/cc/.ssh/id_rsa_chameleon
      ip: ${NODE3_PRIVATE}
      access_ip: ${NODE3_PRIVATE}
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
EOF
echo "Generated: $KUBESPRAY_HOSTS"

# --- Save floating IP for other scripts ---
ENV_FILE="$DEVOPS_DIR/.env"
cat > "$ENV_FILE" << EOF
# Auto-generated by generate-config.sh
FLOATING_IP=${FLOATING_IP}
NODE1_PRIVATE=${NODE1_PRIVATE}
NODE2_PRIVATE=${NODE2_PRIVATE}
NODE3_PRIVATE=${NODE3_PRIVATE}
SSH_KEY=~/.ssh/id_rsa_chameleon
SSH_USER=cc
EOF
echo "Generated: $ENV_FILE"

echo ""
echo "=== All configs generated for floating IP: ${FLOATING_IP} ==="
echo "Next steps:"
echo "  1. ssh-keygen -R ${FLOATING_IP}"
echo "  2. ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/id_rsa_chameleon cc@${FLOATING_IP}"
echo "  3. cd SmartQueue/devops/ansible && ansible-playbook -i inventory/hosts.ini playbooks/pre_k8s.yaml"
