apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: smartqueue-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: postgres
