apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-platform-route-prod
  namespace: smartqueue-prod
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: smartqueue-platform
  to:
    - group: ""
      kind: Service
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-platform-route-canary
  namespace: smartqueue-canary
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: smartqueue-platform
  to:
    - group: ""
      kind: Service
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-platform-route-staging
  namespace: smartqueue-staging
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: smartqueue-platform
  to:
    - group: ""
      kind: Service
