apiVersion: v1
kind: Namespace
metadata:
  name: smartqueue-prod
  labels:
    app.kubernetes.io/part-of: smartqueue
---
apiVersion: v1
kind: Namespace
metadata:
  name: smartqueue-staging
  labels:
    app.kubernetes.io/part-of: smartqueue
