apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartqueue-serving
  labels:
    app: smartqueue-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartqueue-serving
  template:
    metadata:
      labels:
        app: smartqueue-serving
    spec:
      containers:
        - name: serving
          image: node1:5000/smartqueue-serving:v3
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis.smartqueue-platform.svc.cluster.local
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow.smartqueue-platform.svc.cluster.local:5000
            - name: MODEL_URI
              value: runs:/2ce32ba692c54095b4307ae8eb7ba508/model
            - name: MODEL_NAME
              value: smartqueue-ranking
            - name: MODEL_STAGE
              value: Production
            - name: MODEL_VERSION
              value: v2ce32ba6
            - name: MOCK_ON_MLFLOW_FAIL
              value: "false"
            - name: MLFLOW_S3_ENDPOINT_URL
              value: https://chi.tacc.chameleoncloud.org:7480
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: AWS_SECRET_ACCESS_KEY
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 15
            timeoutSeconds: 5
