apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartqueue-serving
  labels:
    app: smartqueue-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartqueue-serving
  template:
    metadata:
      labels:
        app: smartqueue-serving
    spec:
      containers:
        - name: serving
          image: node1:5000/smartqueue-serving:v1
          ports:
            - containerPort: 8000
          env:
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow.smartqueue-platform.svc.cluster.local:5000
            - name: MODEL_URI
              value: runs:/b5cd1cdfbc3649008ed6bd1355e36004/model
            - name: MODEL_VERSION
              value: vb5cd1cdf
            - name: MLFLOW_S3_ENDPOINT_URL
              value: https://chi.tacc.chameleoncloud.org:7480
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: AWS_SECRET_ACCESS_KEY
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 5
