apiVersion: v1
kind: Service
metadata:
  name: smartqueue-serving
  labels:
    app: smartqueue-serving
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: smartqueue-serving
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
